### ISSUE TITLE
An error occurred while retrieving data from the server in Get Token

### ISSUE THREAD

**Issue by bhavikmit** [adplabs/adp-connection-NET#22]
Hi Team,

I am successfully redirecting to my "redirectURL" from ADP Portal, and after that, if I am trying to get Token or Get Data at that time, I am getting below error.
```
An error occurred while retrieving data from the server. Please try again.
ADPClient.ADPException.ADPConnectionException: ADP connection Exception: File not found
   at ADPClient.ADPApiConnection.LoadCertificateFile(String Filename, String SSLKeyPath, String Password) in C:\Users\TBS-013\Downloads\adp-connection-NET-master\adp-connection-NET-master\ADPClient\Connection\ADPApiConnection.cs:line 244
   at ADPClient.ADPApiConnection.SendWebRequest(String url, Dictionary`2 data, AuthenticationHeaderValue authentication, String contentType, String method, String jsonBody) in C:\Users\TBS-013\Downloads\adp-connection-NET-master\adp-connection-NET-master\ADPClient\Connection\ADPApiConnection.cs:line 296
   at ADPClient.AuthorizationCodeConnection.getAccessToken() in C:\Users\TBS-013\Downloads\adp-connection-NET-master\adp-connection-NET-master\ADPClient\Connection\AuthorizationCodeConnection.cs:line 98
   at ADPClient.ADPApiConnection.connect() in C:\Users\TBS-013\Downloads\adp-connection-NET-master\adp-connection-NET-master\ADPClient\Connection\ADPApiConnection.cs:line 78
   at ADPClientWebDemo.marketplaceController.getToken() in C:\Users\TBS-013\Downloads\adp-connection-NET-master\adp-connection-NET-master\ADPClientWebDemo\Controllers\marketplaceController.cs:line 83

```
Here are the credentials which I am using

{
          "clientID": xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "clientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "sslCertPath": "~/Content/certs/Workhorse.pfx",
          "sslKeyPath": "~/Content/certs/Workhorse.key",
          "sslKeyPass": "***********",
          "tokenServerURL": "https://api.adp.com/auth/oauth/v2/token",
          "disconnectURL": "https://api.adp.com/auth/oauth/v2/logout",
          "apiRequestURL": "https://api.adp.com",
          "baseAuthorizationURL": "https://api.adp.com/auth/oauth/v2/authorize",
          "redirectURL": "https://localhost/adp/callback",
          "accessScope": "hr.workerInformationManagement.workerManagement.workerViewing.worker.read hr.workerInformationManagement.workerManagement.associateManagment.associate.read hr.workerInformationManagement.workerManagement.employeeManagement.employee.read",
          "responseType": "code",
          "scope": "openid",
          "defaultexpiration": 3600,
          "grantType": "authorization_code"
}

**Comment by ADPMarketplace** [comment]
Hi,

Can you please provide us with the correlation ID for this error?  A correlation ID is found in the response headers of the API call.

Thanks,
Kirthi Priya Debbadi.

**Comment by itsbrian903v2** [comment]
I changed the SecurityProtocol to make the DEMO work.

ServicePointManager.Expect100Continue = true;
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3 |
                                                       SecurityProtocolType.Tls | SecurityProtocolType.Tls11;

Right before connection.connect();

Give it a try~

**Comment by tkjlochmandy** [comment]
I am able to connect to the ADP APIs with a status of 200 through postman.  I have tried connecting with the same certificate, secret and id via C# and get "Unauthorized".  I have verified that my certificate is being properly dcrypted, so I think that is good to go... thoughts?  What code can I send that will help me figure out where I am going wrong short of credentialed files?
