### ISSUE TITLE
ADPClientDemo & ADPClientWebDemo not working

### ISSUE THREAD

**Issue by ozziecisneros** [adplabs/adp-connection-NET#26]
After building the solution in VS2019, running ADPClientDemo always results in "One or more errors occurred." on line 311 of ADPApiConnection.cs (this is the line: response = client.PostAsync(url, content).Result;). This is the stack trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ADPClient.ADPApiConnection.SendWebRequest(String url, Dictionary`2 data, AuthenticationHeaderValue authentication, String contentType, String method, String jsonBody) in C:\Users\ozzie\source\repos\adp-test\ADPClient\Connection\ADPApiConnection.cs:line 311
   at ADPClient.ADPApiConnection.getAccessToken() in C:\Users\ozzie\source\repos\adp-test\ADPClient\Connection\ADPApiConnection.cs:line 136
   at ADPClient.ADPApiConnection.connect() in C:\Users\ozzie\source\repos\adp-test\ADPClient\Connection\ADPApiConnection.cs:line 77
   at ADPClientDemo.Program.Main(String[] args) in C:\Users\ozzie\source\repos\adp-test\ADPClientDemo\Program.cs:line 39

ADPClientWebDemo only shows a Login link, that when clicked opens up URL: https://bgatewaystag.adp.com/siteminderagent/forms/marketplace/login.fcc?TARGET=-SM-https://iat-api.adp.com:443/auth/oauth/v2/authorize/consent?sessionID=9e8205a0-25fe-4abb-8a83-986ce2fc54b9&action=consent

I use the credentials provided (MKPLDEMO / marketplace1) but the page returns a "Login Failed" message and I cannot run the demo. I've even tried mkpldemo as the user id and that results in the same.

**Comment by Chandakmanish04** [comment]
We were facing same issue, changed framework to 4.7 and its working for us.

**Comment by ozziecisneros** [comment]
Thanks for getting back to me. I am able to successfully run the ADPClientDemo project now. However, the ADPClientWebDemo is still not working. Upon clicking the Login link from the marketplace/index page, it takes me to this url:
https://bgatewaystag.adp.com/siteminderagent/forms/marketplace/login.fcc?TARGET=-SM-https://iat-api.adp.com:443/auth/oauth/v2/authorize/consent?sessionID=085f8e8a-7a71-4596-8d5d-7ae01b149dc7&action=consent
I then proceed to use the provided credentials (MKPLDEMO / marketplace1) but the page returns a "Login Failed" message. I've tried lower and uppercase for the user id and same thing regardless. What am I missing?
